patch:
  variables:
    - name: env
      label: environment
dashboards:
  - name: "keycloak"
    source:
      kind: "Path"
      value: "./examples/dashboard.json"
    destination:
      format: "json"
      path: "./examples/dashboard-new.json"
