{
 "title": "Keycloak Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(keycloak_logins{env=~\"${env}\"}, instance)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins{instance=\"$instance\", job=\"keycloak\", provider=\"keycloak\", env=~\"${env}\"}, realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(keycloak_logins{instance=\"$instance\", job=\"keycloak\", provider=\"keycloak\", realm=\"$realm\", env=~\"${env}\"}, client_id)"
   },
   { "name": "env", "label": "environment" }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\", env=~\"${env}\"}) * 100) / sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\", env=~\"${env}\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\", env=~\"${env}\"}) * 100) / sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\", env=~\"${env}\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\", job=\"keycloak\", env=~\"${env}\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\", job=\"keycloak\", env=~\"${env}\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", job=\"keycloak\", env=~\"${env}\"})",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Logins Per REALM", "type": "grafana-piechart-panel", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 } },
  { "title": "Logins Per CLIENT", "type": "grafana-piechart-panel", "gridPos": { "h": 7, "w": 12, "x": 6, "y": 7 } },
  { "title": "Registrations Per CLIENT", "type": "grafana-piechart-panel", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 } },
  {
   "title": "Logins per REALM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(keycloak_logins{instance=\"$instance\", job=\"keycloak\", env=~\"${env}\"}[1h])) by (realm)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=\"$instance\", job=\"keycloak\", provider=\"keycloak\", realm=\"$realm\", env=~\"${env}\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_logins{instance=\"$instance\", job=\"keycloak\", realm=\"$realm\", provider=\"keycloak\", env=~\"${env}\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors for $ClientId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts{instance=\"$instance\", job=\"keycloak\", provider=\"keycloak\", realm=\"$realm\", client_id=\"$ClientId\", env=~\"${env}\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on relm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations{instance=\"$instance\", job=\"keycloak\", realm=\"$realm\", provider=\"keycloak\", env=~\"${env}\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors for $ClientId",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(keycloak_registrations_errors{instance=\"$instance\", job=\"keycloak\", provider=\"keycloak\", realm=\"$realm\", client_id=\"$ClientId\", env=~\"${env}\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}